### ISSUE TITLE
"tsc" encounter errors

### ISSUE THREAD

**Issue by luckypoem** [aakobordenau/smartdns#4]
hi.

yudeMacBook-Air:smartdns-by-aa-ko brite$ tsc
src/handlers/HandlerBase.ts(3,1): error TS1128: Declaration or statement expected.
src/handlers/HandlerBase.ts(3,17): error TS1005: ';' expected.
src/handlers/HandlerBase.ts(14,14): error TS1005: '=' expected.
src/handlers/HandlerBase.ts(14,28): error TS1005: ',' expected.
src/handlers/HandlerBase.ts(14,48): error TS1005: ',' expected.
src/handlers/HandlerBase.ts(14,82): error TS1109: Expression expected.
src/handlers/HandlerBase.ts(14,83): error TS1005: ';' expected.
src/hooks/HookBase.ts(3,1): error TS1128: Declaration or statement expected.
src/hooks/HookBase.ts(3,17): error TS1005: ';' expected.
src/hooks/HookBase.ts(4,14): error TS1005: '=' expected.
src/hooks/HookBase.ts(4,28): error TS1005: ',' expected.
src/hooks/HookBase.ts(4,45): error TS1005: ';' expected.
src/hooks/HookBase.ts(5,14): error TS1005: '=' expected.
src/hooks/HookBase.ts(5,24): error TS1005: ';' expected.
yudeMacBook-Air:smartdns-by-aa-ko brite$

how to fix the errors?

**Comment by aa-ko** [comment]
Hi, the project compiles fine for me. Are you using a newer version of tsc?

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:~ brite$ node --version
v12.6.0
yudeMacBook-Air:~ brite$ tsc --version
message TS6029: Version 1.5.3
yudeMacBook-Air:~ brite$

my node version is higher than yours,why my tsc version is lower than yours?
it's very strange.

**Comment by aa-ko** [comment]
I believe this won't compile with a tsc major version lower than 2, sorry :( You must update your tsc.

**Comment by luckypoem** [comment]
i use "npm install -g typescript " to install tsc.but don't know how to update the tsc?

tks for the reply

**Comment by luckypoem** [comment]
i know how to do:
rm -rf /usr/local/bin/tsc
npm uninstall -g typescript
npm install -g typescript
tsc --version
it shows:
Version 3.7.4

**Comment by luckypoem** [comment]
but,
yudeMacBook-Air:smartdns-by-aa-ko brite$ tsc
../node-v12.6.0/node-v12.6.0-darwin-x64/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:80:11
    80 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/@types/node/index.d.ts:80:11 - error TS2300: Duplicate identifier 'IteratorResult'.

80 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  ../node-v12.6.0/node-v12.6.0-darwin-x64/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.


Found 2 errors.

yudeMacBook-Air:smartdns-by-aa-ko brite$ 

how to fix the errors?

**Comment by aa-ko** [comment]
I just tried and it also does not work with the latest tsc. Major version 2 works fine though. Try `npm install -g typescript@2.8.3`.

**Comment by luckypoem** [comment]
this time,it's ok,but i have another issue:
here https://github.com/aa-ko/smartdns/blob/master/src/app.ts ,in line 23,i modify 1.1.1.1 to be
208.67.222.222:5353 ,but in the end i ran "node ./dist/app.js", it exited soon.this means the modified dns resolver's address cannnot be with port number?
if i want the new dns resolver with port number,how should i modify the line 23 in https://github.com/aa-ko/smartdns/blob/master/src/app.ts?
